apiVersion: v2
name: k8tz
description: Kubernetes admission controller to inject timezones into Pods and CronJobs
version: 0.11.0
appVersion: "0.11.0"
kubeVersion: ">=1.16.0-0"
icon: https://github.com/k8tz/k8tz/raw/master/assets/k8tz-icon-transparent.png
home: http://k8tz.io
sources:
  - https://github.com/k8tz/k8tz
keywords:
  - timezone
  - timezones
  - admission
  - controller
annotations:
  artifacthub.io/changes: |
    - kind: "changed"
      description: "Update tzdata package to 2022g"
      links:
        - name: "2022g Announcement"
          url: "https://mm.icann.org/pipermail/tz-announce/2022-November/000076.html"
    - kind: "added"
      description: "add option to use daemonset instead of deployment"
    - kind: "added"
      description: "add support for managing certificate with cert-manager"
  artifacthub.io/links: |
    - name: "source"
      url: "https://github.com/k8tz/k8tz"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/license: "Apache-2.0"
